language: swift
osx_image: xcode11.4.1
branches:
only:
- updatedForSwift5

script:
 - xcodebuild -workspace TAU.xcworkspace -scheme TAU -destination 'platform=iOS simulator,OS=13.4,name=iPhone XR' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
