os: osx
language: swift
osx_image: xcode11.4
branches:
 only:
  - updatedForSwift5

script:
 - xcodebuild -workspace TAU.xcworkspace -scheme TAU -destination 'platform:iOS Simulator, id:35FCDE39-9679-4A66-A338-9EE7801F5092, OS:13.4.1, name:iPhone SE (2nd generation)' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
